/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.tienda.Views;

import lombok.Getter;
import lombok.Setter;

/**
 * @author Carlos Varas Alonso
 */
@Getter
@Setter
public class Carrito extends javax.swing.JFrame {

  /**
   * Creates new form Carrito
   */
  public Carrito() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    Container = new javax.swing.JPanel();
    Informacion = new javax.swing.JPanel();
    PrecioTotal = new javax.swing.JLabel();
    ScrollPaneCarritoProductos = new javax.swing.JScrollPane();
    CarritoProductos = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setPreferredSize(new java.awt.Dimension(1445, 1000));
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    Container.setBackground(new java.awt.Color(255, 255, 255));
    Container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    Informacion.setBackground(new java.awt.Color(87, 93, 251));
    Informacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    PrecioTotal.setFont(new java.awt.Font("Inter ExtraBold", 1, 32)); // NOI18N
    PrecioTotal.setForeground(new java.awt.Color(255, 255, 255));
    PrecioTotal.setText("Total: 200€");
    Informacion.add(PrecioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 36, -1, -1));

    Container.add(Informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 72, 1392, 96));

    javax.swing.GroupLayout CarritoProductosLayout = new javax.swing.GroupLayout(CarritoProductos);
    CarritoProductos.setLayout(CarritoProductosLayout);
    CarritoProductosLayout.setHorizontalGroup(
      CarritoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 1383, Short.MAX_VALUE)
    );
    CarritoProductosLayout.setVerticalGroup(
      CarritoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 898, Short.MAX_VALUE)
    );

    ScrollPaneCarritoProductos.setViewportView(CarritoProductos);

    Container.add(ScrollPaneCarritoProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 192, 1385, 795));

    getContentPane().add(Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1445, 1000));

    pack();
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel CarritoProductos;
  private javax.swing.JPanel Container;
  private javax.swing.JPanel Informacion;
  private javax.swing.JLabel PrecioTotal;
  private javax.swing.JScrollPane ScrollPaneCarritoProductos;
  // End of variables declaration//GEN-END:variables
}
