/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.tienda.Views;

import lombok.Getter;
import lombok.Setter;
import org.tienda.Controller.cCarrito;
import org.tienda.Model.Usuarios;

/**
 * @author Carlos Varas Alonso
 */

@Getter
@Setter
public class Carrito extends javax.swing.JFrame {
  private static Usuarios usuario;

  /**
   * Creates new form Carrito
   */
  public Carrito(Usuarios usuario) {
    this.usuario = usuario;
    initComponents();
    cCarrito cCarrito = new cCarrito(this);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
