/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.tienda.views;

import lombok.Getter;
import org.tienda.controller.cProducto;
import org.tienda.model.Productos;

/**
 * @author carlos
 */
@Getter
public class crearProducto extends javax.swing.JFrame {

  public static final int CREAR = 0;
  public static final int EDITAR = 1;
  private int opcion;

  /**
   * Creates new form crearProducto
   */
  public crearProducto(Productos producto, int opcion) {
    this.opcion = opcion;
    initComponents();
    cProducto c = new cProducto(this, producto);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    Container = new javax.swing.JPanel();
    jPanelProducto = new javax.swing.JPanel();
    Boton = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setUndecorated(true);

    Container.setBackground(new java.awt.Color(255, 255, 255));
    Container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanelProducto.setBackground(new java.awt.Color(231, 231, 231));
    jPanelProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    Boton.setBackground(new java.awt.Color(87, 93, 251));
    Boton.setFont(new java.awt.Font("Inter", 1, 16)); // NOI18N
    Boton.setForeground(new java.awt.Color(255, 255, 255));
    jPanelProducto.add(Boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 639, 343, 56));

    jLabel1.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
    jLabel1.setText("jLabel1");
    jPanelProducto.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 91, -1, -1));

    jTextField1.setText("jTextField1");
    jPanelProducto.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 121, 343, 56));

    Container.add(jPanelProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 136, 414, 727));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton Boton;
  private javax.swing.JPanel Container;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanelProducto;
  private javax.swing.JTextField jTextField1;
  // End of variables declaration//GEN-END:variables
}
