/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.tienda.Views;

import com.formdev.flatlaf.FlatIntelliJLaf;

import java.awt.*;
import java.io.File;
import java.io.IOException;
import javax.persistence.NoResultException;
import javax.swing.*;

import lombok.Getter;
import org.tienda.Controller.cForgotPasswordCode;
import org.tienda.Controller.cForgotPasswordPassword;
import org.tienda.Controller.controllerLogin;
import org.tienda.Models.modelForgotPasswordPassword;
import org.tienda.Models.modelLogin;
import org.tienda.Utils.utilsLenguaje;

/**
 * @author Carlos Varas Alonso
 */
@Getter
public class ForgotPasswordPassword extends javax.swing.JFrame {

  private final cForgotPasswordPassword cForgotPasswordPassword;
  private final modelForgotPasswordPassword mForgotPasswordPassword;
  private utilsLenguaje lenguaje;

  /**
   * Creates new form Login
   */
  public ForgotPasswordPassword() {
    try {
      FlatIntelliJLaf.setPreferredFontFamily(Font.createFont(Font.PLAIN, new File("src/main/resources/font/inter/Inter-VariableFont_slnt,wght.ttf")).getFontName());
    } catch (IOException | FontFormatException e) {
      throw new RuntimeException(e);
    }
    FlatIntelliJLaf.setup();
    initComponents();
    this.jTextFieldUsername.requestFocus();
    try {
      this.lenguaje = new utilsLenguaje();
    } catch (IOException e) {
      System.err.println(e.getMessage());
    }
    this.cForgotPasswordPassword = new cForgotPasswordPassword(this, lenguaje);
    this.mForgotPasswordPassword = new modelForgotPasswordPassword(lenguaje);

  }

  public void initTextFields() {
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanelContainer = new javax.swing.JPanel();
    jPanelLogin = new javax.swing.JPanel();
    jLabelForgotPassword = new javax.swing.JLabel();
    jButtonLogin = new javax.swing.JButton();
    jTextFieldUsername = new javax.swing.JTextField();
    jLabelUsername = new javax.swing.JLabel();
    jButtonClose = new javax.swing.JButton();
    jButtonBack = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setBackground(new java.awt.Color(196, 196, 196));
    setUndecorated(true);
    setResizable(false);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanelContainer.setBackground(new java.awt.Color(196, 196, 196));
    jPanelContainer.setPreferredSize(new java.awt.Dimension(1445, 1000));
    jPanelContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanelLogin.setBackground(new java.awt.Color(255, 255, 255));
    jPanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabelForgotPassword.setFont(new java.awt.Font("Inter", 1, 32)); // NOI18N
    jLabelForgotPassword.setForeground(new java.awt.Color(87, 93, 251));
    jLabelForgotPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("lang/es_ES"); // NOI18N
    jLabelForgotPassword.setText(bundle.getString("login.h1")); // NOI18N
    jLabelForgotPassword.setAlignmentX(0.5F);
    jLabelForgotPassword.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jPanelLogin.add(jLabelForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 125, 371, 75));

    jButtonLogin.setBackground(new java.awt.Color(87, 93, 251));
    jButtonLogin.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
    jButtonLogin.setText("Login");
    jPanelLogin.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 381, 343, 56));

    jTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldUsernameActionPerformed(evt);
      }
    });
    jPanelLogin.add(jTextFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 208, 343, 56));

    jLabelUsername.setText(bundle.getString("login.label.username")); // NOI18N
    jPanelLogin.add(jLabelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 178, 340, 24));

    jButtonClose.setBackground(new java.awt.Color(255, 86, 86));
    jButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/svg/x.png"))); // NOI18N
    jButtonClose.setAlignmentX(0.5F);
    jButtonClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButtonClose.setIconTextGap(0);
    jButtonClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
    jButtonClose.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonCloseActionPerformed(evt);
      }
    });
    jPanelLogin.add(jButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 5, 20, 20));

    jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/svg/Group 23.png"))); // NOI18N
    jButtonBack.setBorder(null);
    jButtonBack.setContentAreaFilled(false);
    jPanelLogin.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 57, 38, 38));

    jPanelContainer.add(jPanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 269, 414, 462));

    getContentPane().add(jPanelContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1445, 1000));

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButtonCloseActionPerformed

  private void jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextFieldUsernameActionPerformed

  /**
   * Main.
   *
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ForgotPasswordPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ForgotPasswordPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ForgotPasswordPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ForgotPasswordPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new ForgotPasswordPassword().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonBack;
  private javax.swing.JButton jButtonClose;
  private javax.swing.JButton jButtonLogin;
  private javax.swing.JLabel jLabelForgotPassword;
  private javax.swing.JLabel jLabelUsername;
  private javax.swing.JPanel jPanelContainer;
  private javax.swing.JPanel jPanelLogin;
  private javax.swing.JTextField jTextFieldUsername;
  // End of variables declaration//GEN-END:variables
}
