/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.tienda.Views;

/**
 *
 * @author Carlos Varas Alonso
 */
public class ForgotPasswordPassword extends javax.swing.JFrame {

  /**
   * Creates new form ForgotPasswordPassword
   */
  public ForgotPasswordPassword() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    Container = new javax.swing.JPanel();
    jPanelForgot = new javax.swing.JPanel();
    jButtonBack = new javax.swing.JButton();
    jButtonClose = new javax.swing.JButton();
    jLabelLogin = new javax.swing.JLabel();
    jButtonLogin = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setUndecorated(true);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    Container.setBackground(new java.awt.Color(196, 196, 196));
    Container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanelForgot.setBackground(new java.awt.Color(255, 255, 255));
    jPanelForgot.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/svg/Group 23.png"))); // NOI18N
    jButtonBack.setBorder(null);
    jButtonBack.setContentAreaFilled(false);
    jPanelForgot.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 57, 38, 38));

    jButtonClose.setBackground(new java.awt.Color(255, 86, 86));
    jButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/svg/x.png"))); // NOI18N
    jButtonClose.setAlignmentX(0.5F);
    jButtonClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButtonClose.setIconTextGap(0);
    jButtonClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
    jButtonClose.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonCloseActionPerformed(evt);
      }
    });
    jPanelForgot.add(jButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 7, 20, 20));

    jLabelLogin.setFont(new java.awt.Font("Inter", 1, 32)); // NOI18N
    jLabelLogin.setForeground(new java.awt.Color(87, 93, 251));
    jLabelLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("lang/es_ES"); // NOI18N
    jLabelLogin.setText(bundle.getString("forgot.password.password..h1")); // NOI18N
    jLabelLogin.setAlignmentX(0.5F);
    jLabelLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jPanelForgot.add(jLabelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 125, 371, 75));

    jButtonLogin.setBackground(new java.awt.Color(87, 93, 251));
    jButtonLogin.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
    jButtonLogin.setText(bundle.getString("forgot.button.confirm")); // NOI18N
    jPanelForgot.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 381, 343, 56));

    jLabel1.setText("jLabel1");
    jPanelForgot.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 219, -1, -1));

    jLabel2.setText("Email");
    jPanelForgot.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 267, -1, -1));

    Container.add(jPanelForgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 269, 414, 462));

    getContentPane().add(Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1445, 1000));

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButtonCloseActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ForgotPasswordPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ForgotPasswordPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ForgotPasswordPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ForgotPasswordPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new ForgotPasswordPassword().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel Container;
  private javax.swing.JButton jButtonBack;
  private javax.swing.JButton jButtonClose;
  private javax.swing.JButton jButtonLogin;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabelLogin;
  private javax.swing.JPanel jPanelForgot;
  // End of variables declaration//GEN-END:variables
}
