/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.tienda.views;

import lombok.Getter;
import lombok.Setter;
import org.tienda.controller.cHome;
import org.tienda.model.Usuarios;

/**
 * The type Home user.
 *
 * @author Carlos Varas Alonso
 */
@Getter
@Setter
public class HomeUser extends javax.swing.JFrame {
  private Usuarios usuario;

  /**
   * Creates new form HomeUser
   *
   * @param user the user
   */
  public HomeUser(Usuarios user) {
    initComponents();
    this.usuario = user;
    cHome cHome = new cHome(this);

  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    Container = new javax.swing.JPanel();
    ScrollContainerProducts = new javax.swing.JScrollPane();
    ContainerProducts = new javax.swing.JPanel();
    sideBar = new javax.swing.JPanel();
    signOut = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setUndecorated(true);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    Container.setBackground(new java.awt.Color(255, 255, 255));
    Container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    ContainerProducts.setBackground(new java.awt.Color(255, 255, 255));
    ScrollContainerProducts.setViewportView(ContainerProducts);

    Container.add(ScrollContainerProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 72, 1100, 916));

    sideBar.setBackground(new java.awt.Color(231, 231, 231));
    sideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    signOut.setBackground(new java.awt.Color(255, 86, 86));
    signOut.setFont(new java.awt.Font("Inter", 1, 16)); // NOI18N
    signOut.setForeground(new java.awt.Color(255, 255, 255));
    signOut.setText("Sign Out");
    sideBar.add(signOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 848, 272, 56));

    Container.add(sideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 72, 300, 916));

    getContentPane().add(Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1445, 1000));

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel Container;
  private javax.swing.JPanel ContainerProducts;
  private javax.swing.JScrollPane ScrollContainerProducts;
  private javax.swing.JPanel sideBar;
  private javax.swing.JButton signOut;
  // End of variables declaration//GEN-END:variables
}
