/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.tienda.views;

import lombok.Getter;
import lombok.Setter;
import org.tienda.controller.cHome;
import org.tienda.model.Usuarios;

/**
 * The type Home user.
 *
 * @author Carlos Varas Alonso
 */
@Getter
@Setter
public class HomeUser extends javax.swing.JFrame {

  private Usuarios usuario;
  private cHome chome;

  /**
   * Creates new form HomeUser
   *
   * @param user the user
   */
  public HomeUser(Usuarios user) {
    initComponents();
    this.usuario = user;
    this.chome = new cHome(this);
  }
  

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    Container = new javax.swing.JPanel();
    ScrollContainerProducts = new javax.swing.JScrollPane();
    ContainerProducts = new javax.swing.JPanel();
    sideBar = new javax.swing.JPanel();
    signOut = new javax.swing.JButton();
    titleCategorias = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    containerCategories = new javax.swing.JPanel();
    btnAdd = new javax.swing.JButton();
    Cerrar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setUndecorated(true);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    Container.setBackground(new java.awt.Color(255, 255, 255));
    Container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    ContainerProducts.setBackground(new java.awt.Color(255, 255, 255));
    ScrollContainerProducts.setViewportView(ContainerProducts);

    Container.add(ScrollContainerProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 72, 1100, 916));

    sideBar.setBackground(new java.awt.Color(231, 231, 231));
    sideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    signOut.setBackground(new java.awt.Color(255, 86, 86));
    signOut.setFont(new java.awt.Font("Inter", 1, 16)); // NOI18N
    signOut.setForeground(new java.awt.Color(255, 255, 255));
    signOut.setText("Sign Out");
    sideBar.add(signOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 848, 272, 56));

    titleCategorias.setBackground(new java.awt.Color(87, 93, 251));
    titleCategorias.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
    titleCategorias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setFont(new java.awt.Font("Inter", 2, 16)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Categorias");
    titleCategorias.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 3, 130, 24));

    sideBar.add(titleCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 30));

    containerCategories.setBackground(new java.awt.Color(231, 231, 231));
    sideBar.add(containerCategories, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 280, -1));

    btnAdd.setBackground(new java.awt.Color(137, 238, 102));
    btnAdd.setFont(new java.awt.Font("Inter", 1, 16)); // NOI18N
    btnAdd.setForeground(new java.awt.Color(255, 255, 255));
    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("lang/es_ES"); // NOI18N
    btnAdd.setText(bundle.getString("crearmodificarproducto.button.create")); // NOI18N
    sideBar.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 780, 272, 56));

    Container.add(sideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 72, 300, 916));

    Cerrar.setBackground(new java.awt.Color(255, 86, 86));
    Cerrar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/svg/x.png"))); // NOI18N
    Cerrar.setToolTipText("");
    Cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    Container.add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 4, 20, 20));

    getContentPane().add(Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1445, 1000));

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton Cerrar;
  private javax.swing.JPanel Container;
  private javax.swing.JPanel ContainerProducts;
  private javax.swing.JScrollPane ScrollContainerProducts;
  private javax.swing.JButton btnAdd;
  private javax.swing.JPanel containerCategories;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel sideBar;
  private javax.swing.JButton signOut;
  private javax.swing.JPanel titleCategorias;
  // End of variables declaration//GEN-END:variables
}
