/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.tienda.Views;

import lombok.Getter;
import org.tienda.Controller.controllerRegister;
import org.tienda.Model.modelRegister;
import org.tienda.Utils.utilsLenguaje;

import java.io.IOException;

/**
 * @author Carlos Varas Alonso
 */
@Getter
public class Register extends javax.swing.JFrame {
  private final controllerRegister cRegister;
  private final modelRegister mRegister;
  private utilsLenguaje lenguaje;

  /**
   * Creates new form Register
   */
  public Register() {
    initComponents();
    this.getJTextFieldEmail().requestFocus();
    try {
      this.lenguaje = new utilsLenguaje();
    } catch (IOException e) {
      System.err.println(e.getMessage());
    }
    this.cRegister = new controllerRegister(this, lenguaje);
    this.mRegister = new modelRegister(this, lenguaje);
    mRegister.actualizarBoton(getJButtonClose(), 999);
    getJPanelLogin().putClientProperty("FlatLaf.style", "arc:" + 8);
  }


  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanelContainer = new javax.swing.JPanel();
    jPanelLogin = new javax.swing.JPanel();
    jButtonClose = new javax.swing.JButton();
    jButtonBack = new javax.swing.JButton();
    jLabelRegistrar = new javax.swing.JLabel();
    jLabelEmail = new javax.swing.JLabel();
    jTextFieldEmail = new javax.swing.JTextField();
    jLabelUsername = new javax.swing.JLabel();
    jTextFieldUsername = new javax.swing.JTextField();
    jLabelNombre = new javax.swing.JLabel();
    jTextFieldNombre = new javax.swing.JTextField();
    jLabelApellidos = new javax.swing.JLabel();
    jTextFieldApellidos = new javax.swing.JTextField();
    jLabelPassword = new javax.swing.JLabel();
    jPasswordFieldPassword = new javax.swing.JPasswordField();
    jLabelConCuenta = new javax.swing.JLabel();
    jButtonRegistrarse = new javax.swing.JButton();
    jButtonIniciarSesion = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setUndecorated(true);
    setResizable(false);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanelContainer.setBackground(new java.awt.Color(196, 196, 196));
    jPanelContainer.setPreferredSize(new java.awt.Dimension(1445, 1000));
    jPanelContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanelLogin.setBackground(new java.awt.Color(255, 255, 255));
    jPanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jButtonClose.setBackground(new java.awt.Color(255, 86, 86));
    jButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/svg/x.png"))); // NOI18N
    jButtonClose.setAlignmentX(0.5F);
    jButtonClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButtonClose.setIconTextGap(0);
    jButtonClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
    jButtonClose.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonCloseActionPerformed(evt);
      }
    });
    jPanelLogin.add(jButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 3, 20, 20));

    jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/svg/Group 23.png"))); // NOI18N
    jButtonBack.setBorder(null);
    jButtonBack.setContentAreaFilled(false);
    jPanelLogin.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 38, 38, 38));

    jLabelRegistrar.setFont(new java.awt.Font("Inter", 1, 32)); // NOI18N
    jLabelRegistrar.setForeground(new java.awt.Color(87, 93, 251));
    jLabelRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("lang/es_ES"); // NOI18N
    jLabelRegistrar.setText(bundle.getString("register.h1")); // NOI18N
    jLabelRegistrar.setAlignmentX(0.5F);
    jLabelRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jPanelLogin.add(jLabelRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

    jLabelEmail.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
    jLabelEmail.setText(bundle.getString("email")); // NOI18N
    jPanelLogin.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 113, -1, -1));

    jTextFieldEmail.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
    jPanelLogin.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 143, 343, 56));

    jLabelUsername.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
    jLabelUsername.setText(bundle.getString("Username")); // NOI18N
    jPanelLogin.add(jLabelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 227, -1, -1));

    jTextFieldUsername.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
    jPanelLogin.add(jTextFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 257, 343, 56));

    jLabelNombre.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
    jLabelNombre.setText(bundle.getString("register.label.name")); // NOI18N
    jPanelLogin.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 340, -1, -1));

    jTextFieldNombre.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
    jPanelLogin.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 371, 343, 56));

    jLabelApellidos.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
    jLabelApellidos.setText(bundle.getString("register.label.lastname")); // NOI18N
    jPanelLogin.add(jLabelApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 455, -1, -1));

    jTextFieldApellidos.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
    jPanelLogin.add(jTextFieldApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 485, 343, 56));

    jLabelPassword.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
    jLabelPassword.setText(bundle.getString("register.label.password")); // NOI18N
    jPanelLogin.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 569, -1, -1));

    jPasswordFieldPassword.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
    jPanelLogin.add(jPasswordFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 599, 343, 55));
    jPasswordFieldPassword.getAccessibleContext().setAccessibleDescription("");

    jLabelConCuenta.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
    jLabelConCuenta.setText(bundle.getString("register.label.ConCuenta")); // NOI18N
    jPanelLogin.add(jLabelConCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 763, -1, -1));

    jButtonRegistrarse.setBackground(new java.awt.Color(87, 93, 251));
    jButtonRegistrarse.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    jButtonRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
    jButtonRegistrarse.setText(bundle.getString("register.button.registrarse")); // NOI18N
    jButtonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonRegistrarseActionPerformed(evt);
      }
    });
    jPanelLogin.add(jButtonRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 680, 343, 56));

    jButtonIniciarSesion.setFont(new java.awt.Font("Inter", 1, 16)); // NOI18N
    jButtonIniciarSesion.setForeground(new java.awt.Color(87, 93, 251));
    jButtonIniciarSesion.setText(bundle.getString("register.button.iniciarsesion")); // NOI18N
    jButtonIniciarSesion.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(87, 93, 251)));
    jButtonIniciarSesion.setContentAreaFilled(false);
    jButtonIniciarSesion.setMargin(new java.awt.Insets(2, 14, 5, 14));
    jButtonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonIniciarSesionActionPerformed(evt);
      }
    });
    jPanelLogin.add(jButtonIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 763, -1, -1));

    jPanelContainer.add(jPanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 100, 414, 800));

    getContentPane().add(jPanelContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1445, 1000));

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void jButtonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarSesionActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButtonIniciarSesionActionPerformed

  private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButtonCloseActionPerformed

  private void jButtonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarseActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButtonRegistrarseActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Register().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonBack;
  private javax.swing.JButton jButtonClose;
  private javax.swing.JButton jButtonIniciarSesion;
  private javax.swing.JButton jButtonRegistrarse;
  private javax.swing.JLabel jLabelApellidos;
  private javax.swing.JLabel jLabelConCuenta;
  private javax.swing.JLabel jLabelEmail;
  private javax.swing.JLabel jLabelNombre;
  private javax.swing.JLabel jLabelPassword;
  private javax.swing.JLabel jLabelRegistrar;
  private javax.swing.JLabel jLabelUsername;
  private javax.swing.JPanel jPanelContainer;
  private javax.swing.JPanel jPanelLogin;
  private javax.swing.JPasswordField jPasswordFieldPassword;
  private javax.swing.JTextField jTextFieldApellidos;
  private javax.swing.JTextField jTextFieldEmail;
  private javax.swing.JTextField jTextFieldNombre;
  private javax.swing.JTextField jTextFieldUsername;
  // End of variables declaration//GEN-END:variables
}
