/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.tienda.components;

import lombok.Getter;
import org.tienda.controller.CCrearModificarProducto;
import org.tienda.model.Productos;
import org.tienda.model.Usuarios;
import org.tienda.views.HomeUser;


/**
 * @author Carlos Varas Alonso
 */
@Getter
public class CrearModificarProducto extends javax.swing.JFrame {
  public static final int CREAR = 0;
  public static final int EDITAR = 1;
  private Usuarios usuario;
  private int opcion;

  /**
   * Creates new form crearProducto
   */
  public CrearModificarProducto(Productos producto, Usuarios usuario, int opcion, HomeUser vistaHome) {
    this.opcion = opcion;
    this.usuario = usuario;
    initComponents();
    CCrearModificarProducto c = new CCrearModificarProducto(this, vistaHome, producto);
  }

  public CrearModificarProducto(Usuarios usuario, int opcion, HomeUser vistaHome) {
    this.opcion = opcion;
    this.usuario = usuario;
    initComponents();
    CCrearModificarProducto c = new CCrearModificarProducto(this, vistaHome);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    Container = new javax.swing.JPanel();
    jPanelProducto = new javax.swing.JPanel();
    boton = new javax.swing.JButton();
    titulo = new javax.swing.JLabel();
    nombre = new javax.swing.JLabel();
    jTextFieldNombre = new javax.swing.JTextField();
    descripcion = new javax.swing.JLabel();
    precio = new javax.swing.JLabel();
    jTextFieldPrecio = new javax.swing.JTextField();
    descuento = new javax.swing.JLabel();
    jTextFieldDescuento = new javax.swing.JTextField();
    imagen = new javax.swing.JLabel();
    SeleccionarImagen = new javax.swing.JButton();
    Cerrar = new javax.swing.JButton();
    jTextFieldDescripcion = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setUndecorated(true);

    Container.setBackground(new java.awt.Color(255, 255, 255));
    Container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanelProducto.setBackground(new java.awt.Color(255, 255, 255));
    jPanelProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    boton.setBackground(new java.awt.Color(87, 93, 251));
    boton.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
    boton.setForeground(new java.awt.Color(255, 255, 255));
    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("lang/es_ES"); // NOI18N
    boton.setText(bundle.getString("crearmodificarproducto.button.create")); // NOI18N
    jPanelProducto.add(boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 639, 343, 56));

    titulo.setFont(new java.awt.Font("Inter", 1, 32)); // NOI18N
    titulo.setForeground(new java.awt.Color(87, 93, 251));
    titulo.setText(bundle.getString("crearmodificarproducto.create.h1")); // NOI18N
    jPanelProducto.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 39, -1, -1));

    nombre.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
    nombre.setText(bundle.getString("crearmodificarproducto.label.name")); // NOI18N
    jPanelProducto.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 91, -1, -1));

    jTextFieldNombre.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
    jPanelProducto.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 121, 343, 56));

    descripcion.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
    descripcion.setText(bundle.getString("crearmodificarproducto.label.description")); // NOI18N
    jPanelProducto.add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 192, -1, -1));

    precio.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
    precio.setText(bundle.getString("crearmodificarproducto.label.price")); // NOI18N
    jPanelProducto.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 319, -1, -1));

    jTextFieldPrecio.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
    jPanelProducto.add(jTextFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 349, 343, 56));

    descuento.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
    descuento.setText(bundle.getString("crearmodificarproducto.label.descount")); // NOI18N
    jPanelProducto.add(descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 433, -1, -1));

    jTextFieldDescuento.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
    jPanelProducto.add(jTextFieldDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 463, 343, 56));

    imagen.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
    imagen.setText(bundle.getString("crearmodificarproducto.label.image")); // NOI18N
    jPanelProducto.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 547, -1, -1));

    SeleccionarImagen.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
    SeleccionarImagen.setText(bundle.getString("crearmodificarproducto.button.selectImage")); // NOI18N
    jPanelProducto.add(SeleccionarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 577, 343, 34));

    Cerrar.setBackground(new java.awt.Color(255, 86, 86));
    Cerrar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/svg/x.png"))); // NOI18N
    Cerrar.setToolTipText("");
    Cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jPanelProducto.add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 5, 20, 20));

    jTextFieldDescripcion.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
    jTextFieldDescripcion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    jPanelProducto.add(jTextFieldDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 222, 343, 82));

    Container.add(jPanelProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 414, 727));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton Cerrar;
  private javax.swing.JPanel Container;
  private javax.swing.JButton SeleccionarImagen;
  private javax.swing.JButton boton;
  private javax.swing.JLabel descripcion;
  private javax.swing.JLabel descuento;
  private javax.swing.JLabel imagen;
  private javax.swing.JPanel jPanelProducto;
  private javax.swing.JTextField jTextFieldDescripcion;
  private javax.swing.JTextField jTextFieldDescuento;
  private javax.swing.JTextField jTextFieldNombre;
  private javax.swing.JTextField jTextFieldPrecio;
  private javax.swing.JLabel nombre;
  private javax.swing.JLabel precio;
  private javax.swing.JLabel titulo;
  // End of variables declaration//GEN-END:variables
}
