package org.tienda.Objects;
// Generated 20 dic 2023 19:54:47 by Hibernate Tools 6.3.1.Final

/**
 * CarritoId generated by hbm2java
 */
public class CarritoId implements java.io.Serializable {

  private int idproducto;
  private int idusuario;

  public CarritoId() {
  }

  public CarritoId(int idproducto, int idusuario) {
    this.idproducto = idproducto;
    this.idusuario = idusuario;
  }

  public int getIdproducto() {
    return this.idproducto;
  }

  public void setIdproducto(int idproducto) {
    this.idproducto = idproducto;
  }

  public int getIdusuario() {
    return this.idusuario;
  }

  public void setIdusuario(int idusuario) {
    this.idusuario = idusuario;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof CarritoId))
      return false;
    CarritoId castOther = (CarritoId) other;

    return (this.getIdproducto() == castOther.getIdproducto()) && (this.getIdusuario() == castOther.getIdusuario());
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + this.getIdproducto();
    result = 37 * result + this.getIdusuario();
    return result;
  }

}
