package org.tienda.Objects;
// Generated 20 dic 2023 19:54:47 by Hibernate Tools 6.3.1.Final

import java.sql.Date;
import java.sql.Timestamp;

/**
 * Compras generated by hbm2java
 */
public class Compras implements java.io.Serializable {

  private ComprasId id;
  private Productos productos;
  private Usuarios usuarios;
  private int cantidad;
  private Date fechacompra;
  private Timestamp fechaentrega;

  public Compras() {
  }

  public Compras(ComprasId id, Productos productos, Usuarios usuarios, int cantidad, Date fechacompra,
                 Timestamp fechaentrega) {
    this.id = id;
    this.productos = productos;
    this.usuarios = usuarios;
    this.cantidad = cantidad;
    this.fechacompra = fechacompra;
    this.fechaentrega = fechaentrega;
  }

  public ComprasId getId() {
    return this.id;
  }

  public void setId(ComprasId id) {
    this.id = id;
  }

  public Productos getProductos() {
    return this.productos;
  }

  public void setProductos(Productos productos) {
    this.productos = productos;
  }

  public Usuarios getUsuarios() {
    return this.usuarios;
  }

  public void setUsuarios(Usuarios usuarios) {
    this.usuarios = usuarios;
  }

  public int getCantidad() {
    return this.cantidad;
  }

  public void setCantidad(int cantidad) {
    this.cantidad = cantidad;
  }

  public Date getFechacompra() {
    return this.fechacompra;
  }

  public void setFechacompra(Date fechacompra) {
    this.fechacompra = fechacompra;
  }

  public Timestamp getFechaentrega() {
    return this.fechaentrega;
  }

  public void setFechaentrega(Timestamp fechaentrega) {
    this.fechaentrega = fechaentrega;
  }

}
