package org.tienda.Objects;
// Generated 20 dic 2023 19:54:47 by Hibernate Tools 6.3.1.Final

import java.sql.Timestamp;

/**
 * Historialusuarios generated by hbm2java
 */
public class Historialusuarios implements java.io.Serializable {

  private HistorialusuariosId id;
  private Usuarios usuarios;
  private Timestamp fechafinsesion;

  public Historialusuarios() {
  }

  public Historialusuarios(HistorialusuariosId id, Usuarios usuarios, Timestamp fechafinsesion) {
    this.id = id;
    this.usuarios = usuarios;
    this.fechafinsesion = fechafinsesion;
  }

  public HistorialusuariosId getId() {
    return this.id;
  }

  public void setId(HistorialusuariosId id) {
    this.id = id;
  }

  public Usuarios getUsuarios() {
    return this.usuarios;
  }

  public void setUsuarios(Usuarios usuarios) {
    this.usuarios = usuarios;
  }

  public Timestamp getFechafinsesion() {
    return this.fechafinsesion;
  }

  public void setFechafinsesion(Timestamp fechafinsesion) {
    this.fechafinsesion = fechafinsesion;
  }

}
