package org.tienda.Objects;
// Generated 21 dic 2023 17:36:10 by Hibernate Tools 6.3.1.Final

import java.sql.Timestamp;

/**
 * HistorialusuariosId generated by hbm2java
 */
public class HistorialusuariosId implements java.io.Serializable {

  private Timestamp fechainiciosesion;
  private int idusuario;

  public HistorialusuariosId() {
  }

  public HistorialusuariosId(Timestamp fechainiciosesion, int idusuario) {
    this.fechainiciosesion = fechainiciosesion;
    this.idusuario = idusuario;
  }

  public Timestamp getFechainiciosesion() {
    return this.fechainiciosesion;
  }

  public void setFechainiciosesion(Timestamp fechainiciosesion) {
    this.fechainiciosesion = fechainiciosesion;
  }

  public int getIdusuario() {
    return this.idusuario;
  }

  public void setIdusuario(int idusuario) {
    this.idusuario = idusuario;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof HistorialusuariosId))
      return false;
    HistorialusuariosId castOther = (HistorialusuariosId) other;

    return ((this.getFechainiciosesion() == castOther.getFechainiciosesion())
      || (this.getFechainiciosesion() != null && castOther.getFechainiciosesion() != null
      && this.getFechainiciosesion().equals(castOther.getFechainiciosesion())))
      && (this.getIdusuario() == castOther.getIdusuario());
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + (getFechainiciosesion() == null ? 0 : this.getFechainiciosesion().hashCode());
    result = 37 * result + this.getIdusuario();
    return result;
  }

}
