package org.tienda.Objects;
// Generated 20 dic 2023 19:54:47 by Hibernate Tools 6.3.1.Final

import lombok.Getter;
import lombok.Setter;

import java.sql.Timestamp;

/**
 * Historialusuarios generated by hbm2java
 */
@Setter @Getter public class Historialusuarios implements java.io.Serializable {

  private HistorialusuariosId id;
  private Usuarios usuarios;
  private Timestamp fechafinsesion;

  public Historialusuarios() {
  }

  public Historialusuarios(HistorialusuariosId id, Usuarios usuarios, Timestamp fechafinsesion) {
    this.id = id;
    this.usuarios = usuarios;
    this.fechafinsesion = fechafinsesion;
  }

}
