package org.tienda.Objects;
// Generated 20 dic 2023 19:54:47 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos implements java.io.Serializable {

  private Integer idproducto;
  private String nombre;
  private String descripcion;
  private double precio;
  private Double descuento;
  private String categoria;
  private byte[] imagen;
  private Integer stock;
  private Set carritos = new HashSet(0);
  private Set comprases = new HashSet(0);

  public Productos() {
  }

  public Productos(String nombre, String descripcion, double precio, Double descuento, String categoria, byte[] imagen,
                   Integer stock, Set carritos, Set comprases) {
    this.nombre = nombre;
    this.descripcion = descripcion;
    this.precio = precio;
    this.descuento = descuento;
    this.categoria = categoria;
    this.imagen = imagen;
    this.stock = stock;
    this.carritos = carritos;
    this.comprases = comprases;
  }

  public Integer getIdproducto() {
    return this.idproducto;
  }

  public void setIdproducto(Integer idproducto) {
    this.idproducto = idproducto;
  }

  public String getNombre() {
    return this.nombre;
  }

  public void setNombre(String nombre) {
    this.nombre = nombre;
  }

  public String getDescripcion() {
    return this.descripcion;
  }

  public void setDescripcion(String descripcion) {
    this.descripcion = descripcion;
  }

  public double getPrecio() {
    return this.precio;
  }

  public void setPrecio(double precio) {
    this.precio = precio;
  }

  public Double getDescuento() {
    return this.descuento;
  }

  public void setDescuento(Double descuento) {
    this.descuento = descuento;
  }

  public String getCategoria() {
    return this.categoria;
  }

  public void setCategoria(String categoria) {
    this.categoria = categoria;
  }

  public byte[] getImagen() {
    return this.imagen;
  }

  public void setImagen(byte[] imagen) {
    this.imagen = imagen;
  }

  public Integer getStock() {
    return this.stock;
  }

  public void setStock(Integer stock) {
    this.stock = stock;
  }

  public Set getCarritos() {
    return this.carritos;
  }

  public void setCarritos(Set carritos) {
    this.carritos = carritos;
  }

  public Set getComprases() {
    return this.comprases;
  }

  public void setComprases(Set comprases) {
    this.comprases = comprases;
  }

}
