package org.tienda.Objects;
// Generated 20 dic 2023 19:54:47 by Hibernate Tools 6.3.1.Final

import lombok.Data;

import java.util.HashSet;
import java.util.Set;

@Data
/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

  private Integer idusuario;
  private String username;
  private String password;
  private String nombre;
  private String apellidos;
  private String email;
  private byte[] imagen;
  private String lenguaje;
  private String permisos;
  private String roles;
  private boolean activacion;
  private String codigo;
  private Set historialusuarioses = new HashSet(0);
  private Set carritos = new HashSet(0);
  private Set comprases = new HashSet(0);

  public Usuarios() {
  }

  public Usuarios(String username, String password, String nombre, String apellidos, String email, byte[] imagen,
                  String lenguaje, String permisos, String roles, boolean activacion, String codigo, Set historialusuarioses,
                  Set carritos, Set comprases) {
    this.username = username;
    this.password = password;
    this.nombre = nombre;
    this.apellidos = apellidos;
    this.email = email;
    this.imagen = imagen;
    this.lenguaje = lenguaje;
    this.permisos = permisos;
    this.roles = roles;
    this.activacion = activacion;
    this.codigo = codigo;
    this.historialusuarioses = historialusuarioses;
    this.carritos = carritos;
    this.comprases = comprases;
  }

}
